### ISSUE TITLE
 `<main>': undefined method `slug' for #<Locomotive::Coal::Resources::ContentEntries:0x00007f849de90a10> (NoMethodError)

### ISSUE THREAD

**Issue by DonKoko** [locomotivecms/coal#24]
I am trying to get all content entries but I keep on getting the error for missing slug.
I made a tiny script and it keeps on failing with the error above:
Script:
```
require 'locomotive/coal'
client = Locomotive::Coal::Client.new('...', { email: '...', api_key: '...' })
site_client = client.scope_by('site')

content_type = site_client.contents.news
news = site_client.content_entries(content_type).all

puts news.count
```

Error:
```
Traceback (most recent call last):
	1: from update_news_entries.rb:6:in `<main>'
/Users/donkoko/.rvm/gems/ruby-2.5.3/gems/locomotivecms_coal-1.6.0.beta1/lib/locomotive/coal/client.rb:44:in `content_entries': undefined method `slug' for #<Locomotive::Coal::Resources::ContentEntries:0x00007fcaeafa4828> (NoMethodError)
```

Coal version: `locomotivecms_coal (1.5.1)`
Engine version: `gem 'locomotivecms', github: 'locomotivecms/engine', ref: '9ed6083'`

**Comment by did** [comment]
Alright, not a bug but a misuse of the Coal API.

```ruby
require 'locomotive/coal'
client = Locomotive::Coal::Client.new('...', { email: '...', api_key: '...' })
site_client = client.scope_by('site')

news = site_client.contents.news.all

puts news.count
```

**Comment by DonKoko** [comment]
Thanks for clarifying. For me it was kind of confusing the documentation with the different versions.
